name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set zip filename
        run: echo "zip_filename=t2a_pose_converter-${{ github.ref_name }}.zip" >> $GITHUB_ENV

      - name: Copy LICENSE and NOTICE files
        run: |
          cp -p LICENSE t2a_pose_converter/

      - name: Create zip file
        run: |
          zip -r "${{ env.zip_filename }}" t2a_pose_converter -x "t2a_pose_converter/__pycache__/*" "t2a_pose_converter/**/__pycache__/*"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: ${{ env.zip_filename }}
          draft: true
          generate_release_notes: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}